=== command
BUILDKITE="true" SEMGREP_REPO_NAME="a/repo/name" SEMGREP_REPO_URL="https://random.url.org/some/path" SEMGREP_BRANCH="branch/some-other-branch-name" SEMGREP_JOB_URL="https://another.random.url.org/some/path" SEMGREP_COMMIT="<some_random_commit>" SEMGREP_PR_ID="99999" BUILDKITE_REPO="git@github.com/project_name/project_name.git" BUILDKITE_BRANCH="some/branch-name" BUILDKITE_BUILD_URL="https://buildkite.build.url/something" BUILDKITE_JOB_ID="42" BUILDKITE_PULL_REQUEST="35" BUILDKITE_BUILD_AUTHOR="Environment Test" BUILDKITE_BUILD_AUTHOR_EMAIL="test_environment@test.r2c.dev" BUILDKITE_MESSAGE="some: commit message! foo" BUILDKITE_COMMIT="<MASKED>" SEMGREP_APP_TOKEN="fake-key-from-tests" SEMGREP_USER_AGENT_APPEND="pytest" SEMGREP_SETTINGS_FILE="<MASKED>" SEMGREP_VERSION_CACHE_PATH="<MASKED>" SEMGREP_ENABLE_VERSION_CHECK="0" SEMGREP_SEND_METRICS="off" semgrep ci --no-suppress-errors
=== end of command

=== exit code
2
=== end of exit code

=== stdout - plain

=== end of stdout - plain

=== stderr - plain


┌────────────────┐
│ Debugging Info │
└────────────────┘

  SCAN ENVIRONMENT
  versions    - semgrep <MASKED> on python <MASKED>
  environment - running in environment buildkite, triggering event is
                pull_request

  CONNECTION
  Initializing scan (deployment=org_name, scan_id=12345)
  Enabled products: Code, Supply Chain                    [Errno 2] No such file or directory: '/usr/bin/semgrep-core'
Traceback (most recent call last):
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/commands/wrapper.py", line 37, in wrapper
    func(*args, **kwargs)
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/commands/ci.py", line 436, in ci
    ) = semgrep.run_scan.run_scan(
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/run_scan.py", line 513, in run_scan
    contributions = get_contributions(engine_type)
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/core_runner.py", line 88, in get_contributions
    raw_output = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/semgrep-core'

=== end of stderr - plain