=== command
SEMGREP_USER_AGENT_APPEND="pytest" SEMGREP_SETTINGS_FILE="<MASKED>" SEMGREP_VERSION_CACHE_PATH="<MASKED>" SEMGREP_ENABLE_VERSION_CHECK="0" SEMGREP_SEND_METRICS="off" semgrep --test --strict --config rules/fixtest/test4.yaml targets/fixtest/test4.py
=== end of command

=== exit code
1
=== end of exit code

=== stdout - plain
No unit tests found. See https://semgrep.dev/docs/writing-rules/testing-rules
0/1: 1 fix tests did not pass: 
--------------------------------------------------------------------------------
	âœ– targets/fixtest/test4.fixed.py <> autofix applied to targets/fixtest/test4.py 

	---
	+++
	@@ -2 +2 @@
	-sys.exit(1)
	+exit(1)
	@@ -5 +5 @@
	-sys.exit(2)
	+exit(2)



--------------------------------------------------------------------------------
The following config files produced errors:
	rules/fixtest/test4.yaml: Fatal error at line :1:
 (Sys_error "/rules.jsonnet: Permission denied")
====[ BEGIN error trace ]====
(Sys_error "/rules.jsonnet: Permission denied")
Raised by primitive operation at Stdlib.open_out_gen in file "stdlib.ml", line 331, characters 29-55
Called from Stdlib.open_out_bin in file "stdlib.ml" (inlined), line 339, characters 2-76
Called from Common.write_file in file "src/pfff/commons/Common.ml", line 1271, characters 13-30
Called from Parse_rule.parse_templated_rules in file "src/parsing/Parse_rule.ml", line 1290, characters 2-50
Called from Parse_rule.parse_possibly_templated_rules in file "src/parsing/Parse_rule.ml", line 1350, characters 4-54
Called from Common.with_time in file "src/pfff/commons/Common.ml", line 215, characters 12-16
Called from Run_semgrep.semgrep_with_raw_results_and_exn_handler in file "src/runner/Run_semgrep.ml", line 665, characters 6-97
=====[ END error trace ]=====


=== end of stdout - plain

=== stderr - plain

=== end of stderr - plain