Traceback (most recent call last):
  File "/home/runner/work/semgrep/semgrep/cli/bin/semgrep", line 47, in <module>
    PATH = os.environ["PATH"]
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'PATH'
